name: SpazioFFA
main: com.minespazio.FFA
version: BETA
author: cachorrohdz
commands:
  admin:
    description: admin comando minespazio
    usage: /admin
  lobby:
    description: comando principal solo administradores
    usage: /lobby o salir
    aliases: [salir]
  kits:
    description: comando para abrir menu de kits
    usage: /kits o kit
    aliases: [kit]